### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zoomx** [Slocan/weatherDashboard#1]
It is possible to Telegraph to listen to more than one GW1000?

**Comment by Slocan** [comment]
You can point multiple GW1000 to the endpoint. However, it does not look like they identify themselves except by model and firmware number, so the data for the dashboard might conflict. I don't have multiple GW1000 to test, so the actual behaviour is unknown.
The easiest might be to duplicate the telegraf.conf file, and changing the port on one of them (possibly adding a custom tag for each input, to make the dashboards easier to create). You can then point the GW1000 to separate ports.

**Comment by zoomx** [comment]
Having a different port for each one is a solution that I found first.

You are right, how to identify every GW1000?

I use pwsWD dashboard (python) and it is described that the data pushed by GW1000 have a sort of unique long key at the beginning, 32 chars long.
Sources as a zip are here
https://pwsdashboard.com/hws_download2019.php?id=release2012
the file is the index.php in ecowitt folder, the key go in $passkey1 at the beginning
Withouth the passkey or wrong passkey the passkey is stored in ecco_test.arr



`
#            if passkey is found in post we need 
#              to check with expected passkey(s)
if (array_key_exists ('PASSKEY',$_POST) )      
     {  if     ($_POST['PASSKEY'] == $passkey1) 
             {  # upload is allowed as passkey is correct.  
                $data_stored = $filename1;    # set the file to store the upload
                unset ($_REQUEST['PASSKEY']);}   # remove passkey from upload
#
        elseif (isset ($passkey2) || $_POST['PASSKEY'] == $passkey2) 
             {  $data_stored = $filename2; 
                unset ($_REQUEST['PASSKEY']);}
#
        else {  # not (yet) known passkey -> will be stored local, switch test-mode on
                $message        .= __LINE__.' '.$_POST['PASSKEY'].' needs to be set in index.php ';
                $test_mode      = true;}
        } // eo check passkey(s)
#
#-----------------------------------------------                      
#            no passkey found =>  illegal upload 
#           or you are testing using the browser
else {  $message        .= __LINE__.' NO PASSKEY '; 
        $test_mode      = true;}
#
`

I inserted the code in tags but it seems that was interpreted the same.

**Comment by Slocan** [comment]
Ah, good point. I didn't record it, as I wasn't sure how "confidential" this string should be. It can be added as a label by modifying the last line of telegraf.conf:
form_urlencoded_tag_keys = ["stationtype", "model", "PASSKEY"]
Then, the dashboards could be customized based on that.

**Comment by zoomx** [comment]
Don't know why is named passkey since there is nothing that you can access with that, I believe it is coded starting from MAC address and used by Ecowitt in their site to recognize every single station. GW1000 push data to Ecowitt site without any username, password or API key, the association with users are made using MAC address.

**Comment by zoomx** [comment]
Tanks, I am testing it now!

**Comment by zoomx** [comment]
Test done, it works!
In Telegraf a query could be
`SELECT (mean("tempinf")-32)*5/9 FROM "http_listener_v2" WHERE ("PASSKEY" = 'YOUR_PASSKEY') AND $timeFilter GROUP BY time($__interval) fill(null)`

It seems that the passkey is the MD5 hash of the MAC address.
