### ISSUE TITLE
Panel plugin not found: grafana-clock-panel

### ISSUE THREAD

**Issue by zoomx** [Slocan/weatherDashboard#2]
Launcing the dashboard, without any data at this moment, I get this error

Panel plugin not found: grafana-clock-panel

on the top left panel

I have already installed InfluxDB and Chronograph and I have installed the last Enterprise edition of Grafana

**Comment by Slocan** [comment]
The dashboard uses a plugin to display a simple clock:
You can install it with:
grafana-cli plugins install grafana-clock-panel
See: https://grafana.com/grafana/plugins/grafana-clock-panel/?tab=installation

**Comment by zoomx** [comment]
Got it!
